# Generated by Django 2.2.1 on 2019-05-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0003_auto_20190429_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='zipcode',
            field=models.CharField(default='null', max_length=300, verbose_name='邮编'),
        ),
    ]
