# Generated by Django 2.2.1 on 2019-05-24 11:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0004_adress_zipcode'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adress',
            managers=[
                ('Adress', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
                ('UserInfo', django.db.models.manager.Manager()),
            ],
        ),
    ]
