# Generated by Django 2.2.1 on 2019-05-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0005_auto_20190524_1912'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='adress',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
    ]
