# Generated by Django 2.2.1 on 2019-05-24 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0007_auto_20190429_1625'),
        ('userinfo', '0006_auto_20190524_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNo', models.CharField(max_length=50, verbose_name='商品编号')),
                ('ads', models.CharField(max_length=300, null=True, verbose_name='地址')),
                ('time', models.DateTimeField(auto_now=True)),
                ('acot', models.IntegerField(null=True, verbose_name='总数')),
                ('acount', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='总价')),
                ('orderstatus', models.IntegerField(choices=[(1, '未支付'), (2, '已支付'), (3, '订单取消')], default=1, verbose_name='订单')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='CartInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ccount', models.IntegerField(db_column='cart_count', verbose_name='数量')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserInfo')),
            ],
        ),
    ]
