# Generated by Django 2.2.1 on 2019-05-24 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ads',
        ),
    ]
