# Generated by Django 2.2.1 on 2019-05-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0007_auto_20190429_1625'),
        ('cartinfo', '0002_remove_order_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(to='commodity.Goods'),
        ),
    ]
