# Generated by Django 2.1.7 on 2019-04-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='item',
            new_name='goodnum',
        ),
    ]
