# Generated by Django 2.1.7 on 2019-04-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_auto_20190410_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='normal.png', upload_to='commodity/static/goods/image', verbose_name='商品图片'),
        ),
    ]
