# Generated by Django 2.1.7 on 2019-04-10 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20190410_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='normal.png', upload_to='media', verbose_name='商品图片'),
        ),
    ]
