# Generated by Django 2.1.7 on 2019-04-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_auto_20190410_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='normal.png', upload_to='media/', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='unit',
            field=models.CharField(max_length=30, verbose_name='数量'),
        ),
    ]
