# Generated by Django 2.1.7 on 2019-04-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0005_auto_20190410_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='havebuy',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='购买数量'),
        ),
    ]
