# Generated by Django 2.1.7 on 2019-04-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_goods_havebuy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.CharField(max_length=38, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='normal.png', upload_to='common_static/media/', verbose_name='商品图片'),
        ),
    ]
